# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='status',
            field=models.TextField(default='pending', max_length=1000),
        ),
    ]
